### ISSUE TITLE
Implement other View event handlers

### ISSUE THREAD

**Issue by seletskiy** [seletskiy/go-android-rpc#14] opened 2015-01-18 18:15 UTC
See how `onClick` is implemented:
https://github.com/seletskiy/go-android-rpc/blob/caa6d21ba81891c7e44615b3d464f9188ffb44c9/android/android.go#L28
https://github.com/seletskiy/go-android-rpc/blob/caa6d21ba81891c7e44615b3d464f9188ffb44c9/android/android.go#L149
https://github.com/seletskiy/go-android-rpc/blob/caa6d21ba81891c7e44615b3d464f9188ffb44c9/android/android.go#L206
https://github.com/seletskiy/go-android-rpc/blob/caa6d21ba81891c7e44615b3d464f9188ffb44c9/android/android.go#L244

**Comment by pik4ez** [comment] 2015-01-21 07:23
Is #8 a duplicate of this issue?

**Closed as completed** 2016-05-05 09:54 UTC
Labels: enhancement
